// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/tests/tests.proto

package tests

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import gnmi "github.com/openconfig/gnmi/proto/gnmi"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// OperResult specifies the expected result of an operation. By
// default an operation is expected to succeed.
type GetSetValidationOper_OperResult int32

const (
	GetSetValidationOper_NO_ERROR GetSetValidationOper_OperResult = 0
	GetSetValidationOper_FAILED   GetSetValidationOper_OperResult = 1
)

var GetSetValidationOper_OperResult_name = map[int32]string{
	0: "NO_ERROR",
	1: "FAILED",
}
var GetSetValidationOper_OperResult_value = map[string]int32{
	"NO_ERROR": 0,
	"FAILED":   1,
}

func (x GetSetValidationOper_OperResult) String() string {
	return proto.EnumName(GetSetValidationOper_OperResult_name, int32(x))
}
func (GetSetValidationOper_OperResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_tests_d7f4f41f086a4fc3, []int{11, 0}
}

// Default message to use if test doesn't need any arguments. Default message
// will be type of the field in the message. The name of the field discriminates
// one test from another.
type Default struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Default) Reset()         { *m = Default{} }
func (m *Default) String() string { return proto.CompactTextString(m) }
func (*Default) ProtoMessage()    {}
func (*Default) Descriptor() ([]byte, []int) {
	return fileDescriptor_tests_d7f4f41f086a4fc3, []int{0}
}
func (m *Default) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Default.Unmarshal(m, b)
}
func (m *Default) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Default.Marshal(b, m, deterministic)
}
func (dst *Default) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Default.Merge(dst, src)
}
func (m *Default) XXX_Size() int {
	return xxx_messageInfo_Default.Size(m)
}
func (m *Default) XXX_DiscardUnknown() {
	xxx_messageInfo_Default.DiscardUnknown(m)
}

var xxx_messageInfo_Default proto.InternalMessageInfo

// Message that contains all the information specific to a gnmi Subscribe RPC.
type SubscribeTest struct {
	// Request to use by framework during gnmi Subscribe RPC. If test is part of
	// an extension list, a real subscription isn't created, but the query is
	// registered to receive updates corresponding to its path from subscription
	// of parent test.
	Request *gnmi.SubscribeRequest `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	// log_responses indicates to the test whether it should log all
	// SubscribeResponse messages that are received from the target.
	LogResponses bool `protobuf:"varint,2,opt,name=log_responses,json=logResponses" json:"log_responses,omitempty"`
	// Types that are valid to be assigned to Args:
	//	*SubscribeTest_FakeTest
	//	*SubscribeTest_PathValidation
	//	*SubscribeTest_HasKeys
	//	*SubscribeTest_SchemapathComplete
	//	*SubscribeTest_DataTreePaths
	Args                 isSubscribeTest_Args `protobuf_oneof:"args"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SubscribeTest) Reset()         { *m = SubscribeTest{} }
func (m *SubscribeTest) String() string { return proto.CompactTextString(m) }
func (*SubscribeTest) ProtoMessage()    {}
func (*SubscribeTest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tests_d7f4f41f086a4fc3, []int{1}
}
func (m *SubscribeTest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeTest.Unmarshal(m, b)
}
func (m *SubscribeTest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeTest.Marshal(b, m, deterministic)
}
func (dst *SubscribeTest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeTest.Merge(dst, src)
}
func (m *SubscribeTest) XXX_Size() int {
	return xxx_messageInfo_SubscribeTest.Size(m)
}
func (m *SubscribeTest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeTest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeTest proto.InternalMessageInfo

type isSubscribeTest_Args interface {
	isSubscribeTest_Args()
}

type SubscribeTest_FakeTest struct {
	FakeTest string `protobuf:"bytes,10,opt,name=fake_test,json=fakeTest,oneof"`
}
type SubscribeTest_PathValidation struct {
	PathValidation *Default `protobuf:"bytes,11,opt,name=path_validation,json=pathValidation,oneof"`
}
type SubscribeTest_HasKeys struct {
	HasKeys *HasKeys `protobuf:"bytes,12,opt,name=has_keys,json=hasKeys,oneof"`
}
type SubscribeTest_SchemapathComplete struct {
	SchemapathComplete *SchemaPathComplete `protobuf:"bytes,13,opt,name=schemapath_complete,json=schemapathComplete,oneof"`
}
type SubscribeTest_DataTreePaths struct {
	DataTreePaths *DataTreePaths `protobuf:"bytes,14,opt,name=data_tree_paths,json=dataTreePaths,oneof"`
}

func (*SubscribeTest_FakeTest) isSubscribeTest_Args()           {}
func (*SubscribeTest_PathValidation) isSubscribeTest_Args()     {}
func (*SubscribeTest_HasKeys) isSubscribeTest_Args()            {}
func (*SubscribeTest_SchemapathComplete) isSubscribeTest_Args() {}
func (*SubscribeTest_DataTreePaths) isSubscribeTest_Args()      {}

func (m *SubscribeTest) GetArgs() isSubscribeTest_Args {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *SubscribeTest) GetRequest() *gnmi.SubscribeRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *SubscribeTest) GetLogResponses() bool {
	if m != nil {
		return m.LogResponses
	}
	return false
}

func (m *SubscribeTest) GetFakeTest() string {
	if x, ok := m.GetArgs().(*SubscribeTest_FakeTest); ok {
		return x.FakeTest
	}
	return ""
}

func (m *SubscribeTest) GetPathValidation() *Default {
	if x, ok := m.GetArgs().(*SubscribeTest_PathValidation); ok {
		return x.PathValidation
	}
	return nil
}

func (m *SubscribeTest) GetHasKeys() *HasKeys {
	if x, ok := m.GetArgs().(*SubscribeTest_HasKeys); ok {
		return x.HasKeys
	}
	return nil
}

func (m *SubscribeTest) GetSchemapathComplete() *SchemaPathComplete {
	if x, ok := m.GetArgs().(*SubscribeTest_SchemapathComplete); ok {
		return x.SchemapathComplete
	}
	return nil
}

func (m *SubscribeTest) GetDataTreePaths() *DataTreePaths {
	if x, ok := m.GetArgs().(*SubscribeTest_DataTreePaths); ok {
		return x.DataTreePaths
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SubscribeTest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SubscribeTest_OneofMarshaler, _SubscribeTest_OneofUnmarshaler, _SubscribeTest_OneofSizer, []interface{}{
		(*SubscribeTest_FakeTest)(nil),
		(*SubscribeTest_PathValidation)(nil),
		(*SubscribeTest_HasKeys)(nil),
		(*SubscribeTest_SchemapathComplete)(nil),
		(*SubscribeTest_DataTreePaths)(nil),
	}
}

func _SubscribeTest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SubscribeTest)
	// args
	switch x := m.Args.(type) {
	case *SubscribeTest_FakeTest:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.FakeTest)
	case *SubscribeTest_PathValidation:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PathValidation); err != nil {
			return err
		}
	case *SubscribeTest_HasKeys:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HasKeys); err != nil {
			return err
		}
	case *SubscribeTest_SchemapathComplete:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SchemapathComplete); err != nil {
			return err
		}
	case *SubscribeTest_DataTreePaths:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DataTreePaths); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SubscribeTest.Args has unexpected type %T", x)
	}
	return nil
}

func _SubscribeTest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SubscribeTest)
	switch tag {
	case 10: // args.fake_test
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Args = &SubscribeTest_FakeTest{x}
		return true, err
	case 11: // args.path_validation
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Default)
		err := b.DecodeMessage(msg)
		m.Args = &SubscribeTest_PathValidation{msg}
		return true, err
	case 12: // args.has_keys
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HasKeys)
		err := b.DecodeMessage(msg)
		m.Args = &SubscribeTest_HasKeys{msg}
		return true, err
	case 13: // args.schemapath_complete
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SchemaPathComplete)
		err := b.DecodeMessage(msg)
		m.Args = &SubscribeTest_SchemapathComplete{msg}
		return true, err
	case 14: // args.data_tree_paths
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DataTreePaths)
		err := b.DecodeMessage(msg)
		m.Args = &SubscribeTest_DataTreePaths{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SubscribeTest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SubscribeTest)
	// args
	switch x := m.Args.(type) {
	case *SubscribeTest_FakeTest:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.FakeTest)))
		n += len(x.FakeTest)
	case *SubscribeTest_PathValidation:
		s := proto.Size(x.PathValidation)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SubscribeTest_HasKeys:
		s := proto.Size(x.HasKeys)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SubscribeTest_SchemapathComplete:
		s := proto.Size(x.SchemapathComplete)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SubscribeTest_DataTreePaths:
		s := proto.Size(x.DataTreePaths)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Test specifies a gNMI test. The type indicates the form of test that is
// being performed.
//
// The authentication for the RPC(s) used in the test is specified in
// username_key and password_key. These values are references to an external
// storage of authentication data that can be retrieved by the framework.
type Test struct {
	// Description of the individual test to use for reporting purposes.
	Description string `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	// Amount of time in seconds test is allowed to run before cancelled.
	Timeout int32 `protobuf:"varint,2,opt,name=timeout" json:"timeout,omitempty"`
	// The compiled schema that should be used within the test.
	Schema string `protobuf:"bytes,3,opt,name=schema" json:"schema,omitempty"`
	// Connection parameters to dial into target. If not specified, the one
	// specified by Suite proto is used.
	Connection *Connection `protobuf:"bytes,4,opt,name=connection" json:"connection,omitempty"`
	// Can be extended to include other gNMI RPCs.
	//
	// Types that are valid to be assigned to Type:
	//	*Test_Subscribe
	//	*Test_GetSet
	//	*Test_FakeTest
	Type                 isTest_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_tests_d7f4f41f086a4fc3, []int{2}
}
func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (dst *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(dst, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

type isTest_Type interface {
	isTest_Type()
}

type Test_Subscribe struct {
	Subscribe *SubscribeTest `protobuf:"bytes,10,opt,name=subscribe,oneof"`
}
type Test_GetSet struct {
	GetSet *GetSetTest `protobuf:"bytes,11,opt,name=get_set,json=getSet,oneof"`
}
type Test_FakeTest struct {
	FakeTest *FakeTest `protobuf:"bytes,12,opt,name=fake_test,json=fakeTest,oneof"`
}

func (*Test_Subscribe) isTest_Type() {}
func (*Test_GetSet) isTest_Type()    {}
func (*Test_FakeTest) isTest_Type()  {}

func (m *Test) GetType() isTest_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Test) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Test) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *Test) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

func (m *Test) GetConnection() *Connection {
	if m != nil {
		return m.Connection
	}
	return nil
}

func (m *Test) GetSubscribe() *SubscribeTest {
	if x, ok := m.GetType().(*Test_Subscribe); ok {
		return x.Subscribe
	}
	return nil
}

func (m *Test) GetGetSet() *GetSetTest {
	if x, ok := m.GetType().(*Test_GetSet); ok {
		return x.GetSet
	}
	return nil
}

func (m *Test) GetFakeTest() *FakeTest {
	if x, ok := m.GetType().(*Test_FakeTest); ok {
		return x.FakeTest
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Test) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Test_OneofMarshaler, _Test_OneofUnmarshaler, _Test_OneofSizer, []interface{}{
		(*Test_Subscribe)(nil),
		(*Test_GetSet)(nil),
		(*Test_FakeTest)(nil),
	}
}

func _Test_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Test)
	// type
	switch x := m.Type.(type) {
	case *Test_Subscribe:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Subscribe); err != nil {
			return err
		}
	case *Test_GetSet:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetSet); err != nil {
			return err
		}
	case *Test_FakeTest:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FakeTest); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Test.Type has unexpected type %T", x)
	}
	return nil
}

func _Test_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Test)
	switch tag {
	case 10: // type.subscribe
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SubscribeTest)
		err := b.DecodeMessage(msg)
		m.Type = &Test_Subscribe{msg}
		return true, err
	case 11: // type.get_set
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetSetTest)
		err := b.DecodeMessage(msg)
		m.Type = &Test_GetSet{msg}
		return true, err
	case 12: // type.fake_test
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FakeTest)
		err := b.DecodeMessage(msg)
		m.Type = &Test_FakeTest{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Test_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Test)
	// type
	switch x := m.Type.(type) {
	case *Test_Subscribe:
		s := proto.Size(x.Subscribe)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Test_GetSet:
		s := proto.Size(x.GetSet)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Test_FakeTest:
		s := proto.Size(x.FakeTest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Credentials to use while connecting to target.
type Credentials struct {
	// Resolver value is used to determine which credentials resolver to pick
	// while resolving username and password to use during gNMI connection. By
	// default, plaintext resolver is used if nothing is specified here. If a
	// special resolver is needed, it needs to be registered into global resolvers
	// table.
	Resolver             string   `protobuf:"bytes,1,opt,name=resolver" json:"resolver,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_tests_d7f4f41f086a4fc3, []int{3}
}
func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (dst *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(dst, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetResolver() string {
	if m != nil {
		return m.Resolver
	}
	return ""
}

func (m *Credentials) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// Connection contains required information to be able to dial into a target.
type Connection struct {
	// The name of the target to be set in gNMI messages. For gNMI implementations
	// that can be address multiple targets, this value can be used to specify
	// which one should be the device under test.
	Target string `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
	// Address is used while dialing into gNMI server under test. It needs to be
	// in the form "host:port" or it should resolve to a "host:port".
	Address     string       `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	Credentials *Credentials `protobuf:"bytes,3,opt,name=credentials" json:"credentials,omitempty"`
	// Dial timeout in seconds while connecting to gNMI server under test.
	Timeout              int32    `protobuf:"varint,4,opt,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Connection) Reset()         { *m = Connection{} }
func (m *Connection) String() string { return proto.CompactTextString(m) }
func (*Connection) ProtoMessage()    {}
func (*Connection) Descriptor() ([]byte, []int) {
	return fileDescriptor_tests_d7f4f41f086a4fc3, []int{4}
}
func (m *Connection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connection.Unmarshal(m, b)
}
func (m *Connection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connection.Marshal(b, m, deterministic)
}
func (dst *Connection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connection.Merge(dst, src)
}
func (m *Connection) XXX_Size() int {
	return xxx_messageInfo_Connection.Size(m)
}
func (m *Connection) XXX_DiscardUnknown() {
	xxx_messageInfo_Connection.DiscardUnknown(m)
}

var xxx_messageInfo_Connection proto.InternalMessageInfo

func (m *Connection) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Connection) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Connection) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *Connection) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

// FakeTest is the configuration used for a fake test within the framework.
type FakeTest struct {
	// pass indicates whether the faked test should pass or fail.
	Pass                 bool     `protobuf:"varint,1,opt,name=pass" json:"pass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FakeTest) Reset()         { *m = FakeTest{} }
func (m *FakeTest) String() string { return proto.CompactTextString(m) }
func (*FakeTest) ProtoMessage()    {}
func (*FakeTest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tests_d7f4f41f086a4fc3, []int{5}
}
func (m *FakeTest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FakeTest.Unmarshal(m, b)
}
func (m *FakeTest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FakeTest.Marshal(b, m, deterministic)
}
func (dst *FakeTest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FakeTest.Merge(dst, src)
}
func (m *FakeTest) XXX_Size() int {
	return xxx_messageInfo_FakeTest.Size(m)
}
func (m *FakeTest) XXX_DiscardUnknown() {
	xxx_messageInfo_FakeTest.DiscardUnknown(m)
}

var xxx_messageInfo_FakeTest proto.InternalMessageInfo

func (m *FakeTest) GetPass() bool {
	if m != nil {
		return m.Pass
	}
	return false
}

// HasKeys defines the input for a test that checks that a particular list
// in the schema has a specified set of keys in the list. It can be used
// to check for data completeness of a particular list within the schema.
type HasKeys struct {
	// Path to the list that should be checked.
	Path *gnmi.Path `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	// Items that should be found in the list.
	Item                 []*HasKeys_Item `protobuf:"bytes,2,rep,name=item" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *HasKeys) Reset()         { *m = HasKeys{} }
func (m *HasKeys) String() string { return proto.CompactTextString(m) }
func (*HasKeys) ProtoMessage()    {}
func (*HasKeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_tests_d7f4f41f086a4fc3, []int{6}
}
func (m *HasKeys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasKeys.Unmarshal(m, b)
}
func (m *HasKeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasKeys.Marshal(b, m, deterministic)
}
func (dst *HasKeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasKeys.Merge(dst, src)
}
func (m *HasKeys) XXX_Size() int {
	return xxx_messageInfo_HasKeys.Size(m)
}
func (m *HasKeys) XXX_DiscardUnknown() {
	xxx_messageInfo_HasKeys.DiscardUnknown(m)
}

var xxx_messageInfo_HasKeys proto.InternalMessageInfo

func (m *HasKeys) GetPath() *gnmi.Path {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *HasKeys) GetItem() []*HasKeys_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

// Item defines an entry in the list.
type HasKeys_Item struct {
	Key                  map[string]string `protobuf:"bytes,1,rep,name=key" json:"key,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HasKeys_Item) Reset()         { *m = HasKeys_Item{} }
func (m *HasKeys_Item) String() string { return proto.CompactTextString(m) }
func (*HasKeys_Item) ProtoMessage()    {}
func (*HasKeys_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_tests_d7f4f41f086a4fc3, []int{6, 0}
}
func (m *HasKeys_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasKeys_Item.Unmarshal(m, b)
}
func (m *HasKeys_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasKeys_Item.Marshal(b, m, deterministic)
}
func (dst *HasKeys_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasKeys_Item.Merge(dst, src)
}
func (m *HasKeys_Item) XXX_Size() int {
	return xxx_messageInfo_HasKeys_Item.Size(m)
}
func (m *HasKeys_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_HasKeys_Item.DiscardUnknown(m)
}

var xxx_messageInfo_HasKeys_Item proto.InternalMessageInfo

func (m *HasKeys_Item) GetKey() map[string]string {
	if m != nil {
		return m.Key
	}
	return nil
}

// DataTreePaths specifies a test which allows for checks for the
// existence of particular data within the data tree. It allows recursion
// into lists, or simple queries for data tree paths.
//
// A test which performs a simple check for a data tree path consists
// of a single TestQuery, which specifies the path to be queried. For example,
// to query for the existence of the
// /interfaces/interface[name=eth0]/state/counters/{in,out}-pkts leaves in the
// received data a query specifying:
//
// {
//   steps { name: "interfaces" }
//   steps { name: "interface" key { name: "name" value: "eth0" } }
//   required_paths {
//     prefix {
//       elem { name: "state" }
//       elem { name: "counters" }
//     }
//     paths { elem { name: "in-pkts" } }
//     paths { elem { name: "out-pkts" } }
//   }
// }
//
// is specified. This query is simply expanded to check for the specified paths.
//
// The test also supports querying recursively down the data tree using the
// GetListKeys message within a particular TestQuery. Such a query specifies
// that the query described by the "steps" repeated should be made, and the
// resulting key values of the list found should be assigned into an array.
// Subsequent nested queries can then refer to a value within that array using
// the variable name specified.
//
// For example, if a test wishes to performn a check for
// each interface within the data tree, then nested TestQuery
// messages are required. The first retrieves the keys of the
// /interfaces/interface list from the data tree - and calls a nested TestQuery
// for each key within the /interfaces/interface list (referred to as
// %%interface%%) which performs the actual check:
//
// {
//   steps { name: "interfaces" }
//   steps { name: "interface"  }
//   get_list_keys { var_name: "%%interface%%" }
//   next_query {
//     steps { name: "interfaces" }
//     steps { name: "interface" key_name: "%%interface%%" }
//     required_paths {
//      prefix: {
//        elem: "state"
//        elem: "counters"
//      }
//      paths { elem { name: "in-pkts" } }
//      paths { elem { name: "out-pkts" } }
//    }
//   }
// }
//
// Will execute first a query for /interfaces/interface and assign the
// results to the %%interface%% variable. The child operation will execute
// for each element of the %%interface%% list, and subsequently make a query
// for /interfaces/interface[%%interface%%] where %%interface%% is an individual
// key found in the parent query (e.g., "name=eth0"). The child operation
// checks for the required paths at state/counters/{in,out}-pkts relative to
// the query made in the ListQuery operation.
//
// Where multiple get_list_keys queries are nested, each next_query is called
// for each value of its parent query, such that it is possible to express
// nested list traversals such as:
//
// foreach interface in /interfaces/interface:
//   foreach subinterface of that interface:
//     foreach ipv4 address of that subinterface:
//       ... etc ...
//
//  using nested queries:
//
//  {
//    steps { name: "interfaces" }
//    steps { name: "interface" }
//    get_list_keys { var_name: "%%interface%%" }
//    next_query {
//      steps { name: "interfaces" }
//      steps { name: "interface" key_name: "%%interface%%" }
//      steps { name: "subinterfaces" }
//      steps { name: "subinterface" }
//      get_list_keys { var_name: "%%subinterface%%" }
//      next_query {
//        steps { name: "interfaces" }
//        steps { name: "interface" key_name: "%%interface%%" }
//        steps { name: "subinterfaces" }
//        steps { name: "subinterface" key_name: "%%subinterface%%" }
//        steps { name: "ipv4" }
//        steps { name: "addresses" }
//        steps { name: "address" }
//        get_list_keys { var_name: "%%v4address%%" }
//        next_query {
//          steps { name: "interfaces" }
//          steps { name: "interface" key_name: "%%interface%%" }
//          steps { name: "subinterfaces" }
//          steps { name: "subinterface" key_name: "%%subinterface%%" }
//          steps { name: "ipv4" }
//          steps { name: "addresses" }
//          steps { name: "address"  key_name: "%%v4address%%" }
//          required_paths {
//            ... actual test with required paths ...
//          }
//        }
//      }
//    }
//  }
type DataTreePaths struct {
	// test_oper is the operation to be performed for the test.
	TestOper             *DataTreePaths_TestQuery `protobuf:"bytes,1,opt,name=test_oper,json=testOper" json:"test_oper,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *DataTreePaths) Reset()         { *m = DataTreePaths{} }
func (m *DataTreePaths) String() string { return proto.CompactTextString(m) }
func (*DataTreePaths) ProtoMessage()    {}
func (*DataTreePaths) Descriptor() ([]byte, []int) {
	return fileDescriptor_tests_d7f4f41f086a4fc3, []int{7}
}
func (m *DataTreePaths) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataTreePaths.Unmarshal(m, b)
}
func (m *DataTreePaths) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataTreePaths.Marshal(b, m, deterministic)
}
func (dst *DataTreePaths) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataTreePaths.Merge(dst, src)
}
func (m *DataTreePaths) XXX_Size() int {
	return xxx_messageInfo_DataTreePaths.Size(m)
}
func (m *DataTreePaths) XXX_DiscardUnknown() {
	xxx_messageInfo_DataTreePaths.DiscardUnknown(m)
}

var xxx_messageInfo_DataTreePaths proto.InternalMessageInfo

func (m *DataTreePaths) GetTestOper() *DataTreePaths_TestQuery {
	if m != nil {
		return m.TestOper
	}
	return nil
}

// QueryStep defines a query against the gNMI path of a data tree element.
type DataTreePaths_QueryStep struct {
	// name specifies a name that should be explicitly matched in the
	// gnmi.PathElem the QueryStep is being compared to.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// key specifies the key map which should be explicitly matched in
	// the gnmi.PathElem the QueryStep is being compared to.
	Key map[string]string `protobuf:"bytes,2,rep,name=key" json:"key,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// key_name specifies the name of a variable that has been written to
	// by a previous stage of the test. The value of the key map in the
	// PathElem is substituted for the value currently being iterated over
	// for the variable.
	KeyName              string   `protobuf:"bytes,3,opt,name=key_name,json=keyName" json:"key_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataTreePaths_QueryStep) Reset()         { *m = DataTreePaths_QueryStep{} }
func (m *DataTreePaths_QueryStep) String() string { return proto.CompactTextString(m) }
func (*DataTreePaths_QueryStep) ProtoMessage()    {}
func (*DataTreePaths_QueryStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_tests_d7f4f41f086a4fc3, []int{7, 0}
}
func (m *DataTreePaths_QueryStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataTreePaths_QueryStep.Unmarshal(m, b)
}
func (m *DataTreePaths_QueryStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataTreePaths_QueryStep.Marshal(b, m, deterministic)
}
func (dst *DataTreePaths_QueryStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataTreePaths_QueryStep.Merge(dst, src)
}
func (m *DataTreePaths_QueryStep) XXX_Size() int {
	return xxx_messageInfo_DataTreePaths_QueryStep.Size(m)
}
func (m *DataTreePaths_QueryStep) XXX_DiscardUnknown() {
	xxx_messageInfo_DataTreePaths_QueryStep.DiscardUnknown(m)
}

var xxx_messageInfo_DataTreePaths_QueryStep proto.InternalMessageInfo

func (m *DataTreePaths_QueryStep) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataTreePaths_QueryStep) GetKey() map[string]string {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DataTreePaths_QueryStep) GetKeyName() string {
	if m != nil {
		return m.KeyName
	}
	return ""
}

// TestQuery specifies a single stage of a query within the test.
type DataTreePaths_TestQuery struct {
	// steps specifies the set of QuerySteps that should be made against the
	// data tree to retrieve the data for the operation being performed.
	Steps []*DataTreePaths_QueryStep `protobuf:"bytes,1,rep,name=steps" json:"steps,omitempty"`
	// Types that are valid to be assigned to Type:
	//	*DataTreePaths_TestQuery_GetListKeys
	//	*DataTreePaths_TestQuery_RequiredPaths
	Type                 isDataTreePaths_TestQuery_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *DataTreePaths_TestQuery) Reset()         { *m = DataTreePaths_TestQuery{} }
func (m *DataTreePaths_TestQuery) String() string { return proto.CompactTextString(m) }
func (*DataTreePaths_TestQuery) ProtoMessage()    {}
func (*DataTreePaths_TestQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_tests_d7f4f41f086a4fc3, []int{7, 1}
}
func (m *DataTreePaths_TestQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataTreePaths_TestQuery.Unmarshal(m, b)
}
func (m *DataTreePaths_TestQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataTreePaths_TestQuery.Marshal(b, m, deterministic)
}
func (dst *DataTreePaths_TestQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataTreePaths_TestQuery.Merge(dst, src)
}
func (m *DataTreePaths_TestQuery) XXX_Size() int {
	return xxx_messageInfo_DataTreePaths_TestQuery.Size(m)
}
func (m *DataTreePaths_TestQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_DataTreePaths_TestQuery.DiscardUnknown(m)
}

var xxx_messageInfo_DataTreePaths_TestQuery proto.InternalMessageInfo

type isDataTreePaths_TestQuery_Type interface {
	isDataTreePaths_TestQuery_Type()
}

type DataTreePaths_TestQuery_GetListKeys struct {
	GetListKeys *DataTreePaths_ListQuery `protobuf:"bytes,2,opt,name=get_list_keys,json=getListKeys,oneof"`
}
type DataTreePaths_TestQuery_RequiredPaths struct {
	RequiredPaths *DataTreePaths_RequiredPaths `protobuf:"bytes,3,opt,name=required_paths,json=requiredPaths,oneof"`
}

func (*DataTreePaths_TestQuery_GetListKeys) isDataTreePaths_TestQuery_Type()   {}
func (*DataTreePaths_TestQuery_RequiredPaths) isDataTreePaths_TestQuery_Type() {}

func (m *DataTreePaths_TestQuery) GetType() isDataTreePaths_TestQuery_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *DataTreePaths_TestQuery) GetSteps() []*DataTreePaths_QueryStep {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *DataTreePaths_TestQuery) GetGetListKeys() *DataTreePaths_ListQuery {
	if x, ok := m.GetType().(*DataTreePaths_TestQuery_GetListKeys); ok {
		return x.GetListKeys
	}
	return nil
}

func (m *DataTreePaths_TestQuery) GetRequiredPaths() *DataTreePaths_RequiredPaths {
	if x, ok := m.GetType().(*DataTreePaths_TestQuery_RequiredPaths); ok {
		return x.RequiredPaths
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*DataTreePaths_TestQuery) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _DataTreePaths_TestQuery_OneofMarshaler, _DataTreePaths_TestQuery_OneofUnmarshaler, _DataTreePaths_TestQuery_OneofSizer, []interface{}{
		(*DataTreePaths_TestQuery_GetListKeys)(nil),
		(*DataTreePaths_TestQuery_RequiredPaths)(nil),
	}
}

func _DataTreePaths_TestQuery_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*DataTreePaths_TestQuery)
	// type
	switch x := m.Type.(type) {
	case *DataTreePaths_TestQuery_GetListKeys:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetListKeys); err != nil {
			return err
		}
	case *DataTreePaths_TestQuery_RequiredPaths:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RequiredPaths); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("DataTreePaths_TestQuery.Type has unexpected type %T", x)
	}
	return nil
}

func _DataTreePaths_TestQuery_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*DataTreePaths_TestQuery)
	switch tag {
	case 2: // type.get_list_keys
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DataTreePaths_ListQuery)
		err := b.DecodeMessage(msg)
		m.Type = &DataTreePaths_TestQuery_GetListKeys{msg}
		return true, err
	case 3: // type.required_paths
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DataTreePaths_RequiredPaths)
		err := b.DecodeMessage(msg)
		m.Type = &DataTreePaths_TestQuery_RequiredPaths{msg}
		return true, err
	default:
		return false, nil
	}
}

func _DataTreePaths_TestQuery_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*DataTreePaths_TestQuery)
	// type
	switch x := m.Type.(type) {
	case *DataTreePaths_TestQuery_GetListKeys:
		s := proto.Size(x.GetListKeys)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *DataTreePaths_TestQuery_RequiredPaths:
		s := proto.Size(x.RequiredPaths)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// ListQuery specifies an operation that retrieves the keys from a list.
type DataTreePaths_ListQuery struct {
	// var_name specifies the variable name by which the key values will
	// be referred to in subsequent queries.
	VarName string `protobuf:"bytes,1,opt,name=var_name,json=varName" json:"var_name,omitempty"`
	// next_query specifies a query that should be run for each key that
	// is retrieved by the ListQuery operation.
	NextQuery            *DataTreePaths_TestQuery `protobuf:"bytes,2,opt,name=next_query,json=nextQuery" json:"next_query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *DataTreePaths_ListQuery) Reset()         { *m = DataTreePaths_ListQuery{} }
func (m *DataTreePaths_ListQuery) String() string { return proto.CompactTextString(m) }
func (*DataTreePaths_ListQuery) ProtoMessage()    {}
func (*DataTreePaths_ListQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_tests_d7f4f41f086a4fc3, []int{7, 2}
}
func (m *DataTreePaths_ListQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataTreePaths_ListQuery.Unmarshal(m, b)
}
func (m *DataTreePaths_ListQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataTreePaths_ListQuery.Marshal(b, m, deterministic)
}
func (dst *DataTreePaths_ListQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataTreePaths_ListQuery.Merge(dst, src)
}
func (m *DataTreePaths_ListQuery) XXX_Size() int {
	return xxx_messageInfo_DataTreePaths_ListQuery.Size(m)
}
func (m *DataTreePaths_ListQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_DataTreePaths_ListQuery.DiscardUnknown(m)
}

var xxx_messageInfo_DataTreePaths_ListQuery proto.InternalMessageInfo

func (m *DataTreePaths_ListQuery) GetVarName() string {
	if m != nil {
		return m.VarName
	}
	return ""
}

func (m *DataTreePaths_ListQuery) GetNextQuery() *DataTreePaths_TestQuery {
	if m != nil {
		return m.NextQuery
	}
	return nil
}

// RequiredPaths specifies an operation that checks for paths within
// the data tree.
type DataTreePaths_RequiredPaths struct {
	// prefix is a common prefix for the paths within the required_paths
	// list.
	Prefix *gnmi.Path `protobuf:"bytes,1,opt,name=prefix" json:"prefix,omitempty"`
	// paths is the set of paths that are to be checked for.
	Paths                []*gnmi.Path `protobuf:"bytes,2,rep,name=paths" json:"paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DataTreePaths_RequiredPaths) Reset()         { *m = DataTreePaths_RequiredPaths{} }
func (m *DataTreePaths_RequiredPaths) String() string { return proto.CompactTextString(m) }
func (*DataTreePaths_RequiredPaths) ProtoMessage()    {}
func (*DataTreePaths_RequiredPaths) Descriptor() ([]byte, []int) {
	return fileDescriptor_tests_d7f4f41f086a4fc3, []int{7, 3}
}
func (m *DataTreePaths_RequiredPaths) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataTreePaths_RequiredPaths.Unmarshal(m, b)
}
func (m *DataTreePaths_RequiredPaths) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataTreePaths_RequiredPaths.Marshal(b, m, deterministic)
}
func (dst *DataTreePaths_RequiredPaths) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataTreePaths_RequiredPaths.Merge(dst, src)
}
func (m *DataTreePaths_RequiredPaths) XXX_Size() int {
	return xxx_messageInfo_DataTreePaths_RequiredPaths.Size(m)
}
func (m *DataTreePaths_RequiredPaths) XXX_DiscardUnknown() {
	xxx_messageInfo_DataTreePaths_RequiredPaths.DiscardUnknown(m)
}

var xxx_messageInfo_DataTreePaths_RequiredPaths proto.InternalMessageInfo

func (m *DataTreePaths_RequiredPaths) GetPrefix() *gnmi.Path {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *DataTreePaths_RequiredPaths) GetPaths() []*gnmi.Path {
	if m != nil {
		return m.Paths
	}
	return nil
}

// SchemaPathComplete defines the input for a test that checks that at least
// one instance of a particular schema path is sent to the test framework. It
// can be used to check for path coverage of a particular target.
type SchemaPathComplete struct {
	// prefix is a gNMI path that should be appended to each path in the
	// paths list to form an absolute schema path.
	Prefix *gnmi.Path `protobuf:"bytes,2,opt,name=prefix" json:"prefix,omitempty"`
	// paths is the list of paths that are expected to be received by the
	// test framework.
	Path                 []*gnmi.Path `protobuf:"bytes,1,rep,name=path" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SchemaPathComplete) Reset()         { *m = SchemaPathComplete{} }
func (m *SchemaPathComplete) String() string { return proto.CompactTextString(m) }
func (*SchemaPathComplete) ProtoMessage()    {}
func (*SchemaPathComplete) Descriptor() ([]byte, []int) {
	return fileDescriptor_tests_d7f4f41f086a4fc3, []int{8}
}
func (m *SchemaPathComplete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaPathComplete.Unmarshal(m, b)
}
func (m *SchemaPathComplete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaPathComplete.Marshal(b, m, deterministic)
}
func (dst *SchemaPathComplete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaPathComplete.Merge(dst, src)
}
func (m *SchemaPathComplete) XXX_Size() int {
	return xxx_messageInfo_SchemaPathComplete.Size(m)
}
func (m *SchemaPathComplete) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaPathComplete.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaPathComplete proto.InternalMessageInfo

func (m *SchemaPathComplete) GetPrefix() *gnmi.Path {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *SchemaPathComplete) GetPath() []*gnmi.Path {
	if m != nil {
		return m.Path
	}
	return nil
}

// GetSetTest contains all the information specific to a configuration
// test - which is expected to use RPCs to interact with configuration. Set is
// used to change the configuration, and Get or Subscribe can be used to
// retrieve configuration values to verify the target's initial or final states.
type GetSetTest struct {
	// Types that are valid to be assigned to Args:
	//	*GetSetTest_OperValidation
	Args                 isGetSetTest_Args `protobuf_oneof:"args"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetSetTest) Reset()         { *m = GetSetTest{} }
func (m *GetSetTest) String() string { return proto.CompactTextString(m) }
func (*GetSetTest) ProtoMessage()    {}
func (*GetSetTest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tests_d7f4f41f086a4fc3, []int{9}
}
func (m *GetSetTest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSetTest.Unmarshal(m, b)
}
func (m *GetSetTest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSetTest.Marshal(b, m, deterministic)
}
func (dst *GetSetTest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSetTest.Merge(dst, src)
}
func (m *GetSetTest) XXX_Size() int {
	return xxx_messageInfo_GetSetTest.Size(m)
}
func (m *GetSetTest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSetTest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSetTest proto.InternalMessageInfo

type isGetSetTest_Args interface {
	isGetSetTest_Args()
}

type GetSetTest_OperValidation struct {
	OperValidation *GetSetValidationTest `protobuf:"bytes,10,opt,name=oper_validation,json=operValidation,oneof"`
}

func (*GetSetTest_OperValidation) isGetSetTest_Args() {}

func (m *GetSetTest) GetArgs() isGetSetTest_Args {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *GetSetTest) GetOperValidation() *GetSetValidationTest {
	if x, ok := m.GetArgs().(*GetSetTest_OperValidation); ok {
		return x.OperValidation
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GetSetTest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GetSetTest_OneofMarshaler, _GetSetTest_OneofUnmarshaler, _GetSetTest_OneofSizer, []interface{}{
		(*GetSetTest_OperValidation)(nil),
	}
}

func _GetSetTest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GetSetTest)
	// args
	switch x := m.Args.(type) {
	case *GetSetTest_OperValidation:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OperValidation); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("GetSetTest.Args has unexpected type %T", x)
	}
	return nil
}

func _GetSetTest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GetSetTest)
	switch tag {
	case 10: // args.oper_validation
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetSetValidationTest)
		err := b.DecodeMessage(msg)
		m.Args = &GetSetTest_OperValidation{msg}
		return true, err
	default:
		return false, nil
	}
}

func _GetSetTest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GetSetTest)
	// args
	switch x := m.Args.(type) {
	case *GetSetTest_OperValidation:
		s := proto.Size(x.OperValidation)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// GetSetValidationTest describes a test that validates configuration sets
// on a target. It does not validate the underlying behaviour of the system,
// but restricts itself to validating that setting and retrieving configuration
// returns the expected result.
//
// The expected test methodology is as follows:
//   1. Set the configuration of the target to a "known good" initial state.
//   2. Validate that the configuration running on the target matches this
//      state.
//   3. Perform an update or replace operation on the configuration.
//   4. Validate that the new state of the target matches that which is
//      expected.
type GetSetValidationTest struct {
	// initialise_oper is the operation to initialise the target. It may consist
	// of a configuration to be set and/or get request that validates the target's
	// current state.
	InitialiseOper *GetSetValidationOper `protobuf:"bytes,1,opt,name=initialise_oper,json=initialiseOper" json:"initialise_oper,omitempty"`
	// test_oper is the operation that is under test in the validation test.  The
	// Get and/or Set operations may be set within the operation such that the
	// test can validate a set, a set followed by a get, or solely a get
	// operation.
	TestOper             *GetSetValidationOper `protobuf:"bytes,2,opt,name=test_oper,json=testOper" json:"test_oper,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetSetValidationTest) Reset()         { *m = GetSetValidationTest{} }
func (m *GetSetValidationTest) String() string { return proto.CompactTextString(m) }
func (*GetSetValidationTest) ProtoMessage()    {}
func (*GetSetValidationTest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tests_d7f4f41f086a4fc3, []int{10}
}
func (m *GetSetValidationTest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSetValidationTest.Unmarshal(m, b)
}
func (m *GetSetValidationTest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSetValidationTest.Marshal(b, m, deterministic)
}
func (dst *GetSetValidationTest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSetValidationTest.Merge(dst, src)
}
func (m *GetSetValidationTest) XXX_Size() int {
	return xxx_messageInfo_GetSetValidationTest.Size(m)
}
func (m *GetSetValidationTest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSetValidationTest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSetValidationTest proto.InternalMessageInfo

func (m *GetSetValidationTest) GetInitialiseOper() *GetSetValidationOper {
	if m != nil {
		return m.InitialiseOper
	}
	return nil
}

func (m *GetSetValidationTest) GetTestOper() *GetSetValidationOper {
	if m != nil {
		return m.TestOper
	}
	return nil
}

// GetSetValidationOper describes an individual operation within a
// GetSetValidationTest. If the message consists of:
//
//  * Solely a SetRequest - the SetRequest is sent to the test target, and the
//    result checked against the expected error status in set_ok.
//  * Solely a GetRequest - the GetRequest is sent to the test target, and the
//    result checked against the expected GetResponse.
//  * Both a SetRequest and a GetRequest - the SetRequest is sent to the test
//    target, and the return value compared against set_ok. Subsequently, the
//    GetRequest is sent to the test target, the return code compared to get_ok
//    and the GetResponse compared to the expected GetResponse.
type GetSetValidationOper struct {
	// Types that are valid to be assigned to Setrequest:
	//	*GetSetValidationOper_Set
	//	*GetSetValidationOper_CommonSetrequest
	Setrequest isGetSetValidationOper_Setrequest `protobuf_oneof:"setrequest"`
	// set_ok specifies whether the Set RPC should be successful.
	SetOk GetSetValidationOper_OperResult `protobuf:"varint,10,opt,name=set_ok,json=setOk,enum=tests.GetSetValidationOper_OperResult" json:"set_ok,omitempty"`
	// Types that are valid to be assigned to Getrequest:
	//	*GetSetValidationOper_Get
	//	*GetSetValidationOper_CommonGetrequest
	Getrequest isGetSetValidationOper_Getrequest `protobuf_oneof:"getrequest"`
	GetOk      GetSetValidationOper_OperResult   `protobuf:"varint,20,opt,name=get_ok,json=getOk,enum=tests.GetSetValidationOper_OperResult" json:"get_ok,omitempty"`
	// Types that are valid to be assigned to Getresponse:
	//	*GetSetValidationOper_GetResponse
	//	*GetSetValidationOper_CommonGetresponse
	Getresponse          isGetSetValidationOper_Getresponse `protobuf_oneof:"getresponse"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *GetSetValidationOper) Reset()         { *m = GetSetValidationOper{} }
func (m *GetSetValidationOper) String() string { return proto.CompactTextString(m) }
func (*GetSetValidationOper) ProtoMessage()    {}
func (*GetSetValidationOper) Descriptor() ([]byte, []int) {
	return fileDescriptor_tests_d7f4f41f086a4fc3, []int{11}
}
func (m *GetSetValidationOper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSetValidationOper.Unmarshal(m, b)
}
func (m *GetSetValidationOper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSetValidationOper.Marshal(b, m, deterministic)
}
func (dst *GetSetValidationOper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSetValidationOper.Merge(dst, src)
}
func (m *GetSetValidationOper) XXX_Size() int {
	return xxx_messageInfo_GetSetValidationOper.Size(m)
}
func (m *GetSetValidationOper) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSetValidationOper.DiscardUnknown(m)
}

var xxx_messageInfo_GetSetValidationOper proto.InternalMessageInfo

type isGetSetValidationOper_Setrequest interface {
	isGetSetValidationOper_Setrequest()
}
type isGetSetValidationOper_Getrequest interface {
	isGetSetValidationOper_Getrequest()
}
type isGetSetValidationOper_Getresponse interface {
	isGetSetValidationOper_Getresponse()
}

type GetSetValidationOper_Set struct {
	Set *gnmi.SetRequest `protobuf:"bytes,1,opt,name=set,oneof"`
}
type GetSetValidationOper_CommonSetrequest struct {
	CommonSetrequest string `protobuf:"bytes,2,opt,name=common_setrequest,json=commonSetrequest,oneof"`
}
type GetSetValidationOper_Get struct {
	Get *gnmi.GetRequest `protobuf:"bytes,11,opt,name=get,oneof"`
}
type GetSetValidationOper_CommonGetrequest struct {
	CommonGetrequest string `protobuf:"bytes,12,opt,name=common_getrequest,json=commonGetrequest,oneof"`
}
type GetSetValidationOper_GetResponse struct {
	GetResponse *gnmi.GetResponse `protobuf:"bytes,21,opt,name=get_response,json=getResponse,oneof"`
}
type GetSetValidationOper_CommonGetresponse struct {
	CommonGetresponse string `protobuf:"bytes,22,opt,name=common_getresponse,json=commonGetresponse,oneof"`
}

func (*GetSetValidationOper_Set) isGetSetValidationOper_Setrequest()                {}
func (*GetSetValidationOper_CommonSetrequest) isGetSetValidationOper_Setrequest()   {}
func (*GetSetValidationOper_Get) isGetSetValidationOper_Getrequest()                {}
func (*GetSetValidationOper_CommonGetrequest) isGetSetValidationOper_Getrequest()   {}
func (*GetSetValidationOper_GetResponse) isGetSetValidationOper_Getresponse()       {}
func (*GetSetValidationOper_CommonGetresponse) isGetSetValidationOper_Getresponse() {}

func (m *GetSetValidationOper) GetSetrequest() isGetSetValidationOper_Setrequest {
	if m != nil {
		return m.Setrequest
	}
	return nil
}
func (m *GetSetValidationOper) GetGetrequest() isGetSetValidationOper_Getrequest {
	if m != nil {
		return m.Getrequest
	}
	return nil
}
func (m *GetSetValidationOper) GetGetresponse() isGetSetValidationOper_Getresponse {
	if m != nil {
		return m.Getresponse
	}
	return nil
}

func (m *GetSetValidationOper) GetSet() *gnmi.SetRequest {
	if x, ok := m.GetSetrequest().(*GetSetValidationOper_Set); ok {
		return x.Set
	}
	return nil
}

func (m *GetSetValidationOper) GetCommonSetrequest() string {
	if x, ok := m.GetSetrequest().(*GetSetValidationOper_CommonSetrequest); ok {
		return x.CommonSetrequest
	}
	return ""
}

func (m *GetSetValidationOper) GetSetOk() GetSetValidationOper_OperResult {
	if m != nil {
		return m.SetOk
	}
	return GetSetValidationOper_NO_ERROR
}

func (m *GetSetValidationOper) GetGet() *gnmi.GetRequest {
	if x, ok := m.GetGetrequest().(*GetSetValidationOper_Get); ok {
		return x.Get
	}
	return nil
}

func (m *GetSetValidationOper) GetCommonGetrequest() string {
	if x, ok := m.GetGetrequest().(*GetSetValidationOper_CommonGetrequest); ok {
		return x.CommonGetrequest
	}
	return ""
}

func (m *GetSetValidationOper) GetGetOk() GetSetValidationOper_OperResult {
	if m != nil {
		return m.GetOk
	}
	return GetSetValidationOper_NO_ERROR
}

func (m *GetSetValidationOper) GetGetResponse() *gnmi.GetResponse {
	if x, ok := m.GetGetresponse().(*GetSetValidationOper_GetResponse); ok {
		return x.GetResponse
	}
	return nil
}

func (m *GetSetValidationOper) GetCommonGetresponse() string {
	if x, ok := m.GetGetresponse().(*GetSetValidationOper_CommonGetresponse); ok {
		return x.CommonGetresponse
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GetSetValidationOper) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GetSetValidationOper_OneofMarshaler, _GetSetValidationOper_OneofUnmarshaler, _GetSetValidationOper_OneofSizer, []interface{}{
		(*GetSetValidationOper_Set)(nil),
		(*GetSetValidationOper_CommonSetrequest)(nil),
		(*GetSetValidationOper_Get)(nil),
		(*GetSetValidationOper_CommonGetrequest)(nil),
		(*GetSetValidationOper_GetResponse)(nil),
		(*GetSetValidationOper_CommonGetresponse)(nil),
	}
}

func _GetSetValidationOper_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GetSetValidationOper)
	// setrequest
	switch x := m.Setrequest.(type) {
	case *GetSetValidationOper_Set:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Set); err != nil {
			return err
		}
	case *GetSetValidationOper_CommonSetrequest:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.CommonSetrequest)
	case nil:
	default:
		return fmt.Errorf("GetSetValidationOper.Setrequest has unexpected type %T", x)
	}
	// getrequest
	switch x := m.Getrequest.(type) {
	case *GetSetValidationOper_Get:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Get); err != nil {
			return err
		}
	case *GetSetValidationOper_CommonGetrequest:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.CommonGetrequest)
	case nil:
	default:
		return fmt.Errorf("GetSetValidationOper.Getrequest has unexpected type %T", x)
	}
	// getresponse
	switch x := m.Getresponse.(type) {
	case *GetSetValidationOper_GetResponse:
		b.EncodeVarint(21<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetResponse); err != nil {
			return err
		}
	case *GetSetValidationOper_CommonGetresponse:
		b.EncodeVarint(22<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.CommonGetresponse)
	case nil:
	default:
		return fmt.Errorf("GetSetValidationOper.Getresponse has unexpected type %T", x)
	}
	return nil
}

func _GetSetValidationOper_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GetSetValidationOper)
	switch tag {
	case 1: // setrequest.set
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(gnmi.SetRequest)
		err := b.DecodeMessage(msg)
		m.Setrequest = &GetSetValidationOper_Set{msg}
		return true, err
	case 2: // setrequest.common_setrequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Setrequest = &GetSetValidationOper_CommonSetrequest{x}
		return true, err
	case 11: // getrequest.get
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(gnmi.GetRequest)
		err := b.DecodeMessage(msg)
		m.Getrequest = &GetSetValidationOper_Get{msg}
		return true, err
	case 12: // getrequest.common_getrequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Getrequest = &GetSetValidationOper_CommonGetrequest{x}
		return true, err
	case 21: // getresponse.get_response
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(gnmi.GetResponse)
		err := b.DecodeMessage(msg)
		m.Getresponse = &GetSetValidationOper_GetResponse{msg}
		return true, err
	case 22: // getresponse.common_getresponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Getresponse = &GetSetValidationOper_CommonGetresponse{x}
		return true, err
	default:
		return false, nil
	}
}

func _GetSetValidationOper_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GetSetValidationOper)
	// setrequest
	switch x := m.Setrequest.(type) {
	case *GetSetValidationOper_Set:
		s := proto.Size(x.Set)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GetSetValidationOper_CommonSetrequest:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.CommonSetrequest)))
		n += len(x.CommonSetrequest)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// getrequest
	switch x := m.Getrequest.(type) {
	case *GetSetValidationOper_Get:
		s := proto.Size(x.Get)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GetSetValidationOper_CommonGetrequest:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.CommonGetrequest)))
		n += len(x.CommonGetrequest)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// getresponse
	switch x := m.Getresponse.(type) {
	case *GetSetValidationOper_GetResponse:
		s := proto.Size(x.GetResponse)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GetSetValidationOper_CommonGetresponse:
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(len(x.CommonGetresponse)))
		n += len(x.CommonGetresponse)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Default)(nil), "tests.Default")
	proto.RegisterType((*SubscribeTest)(nil), "tests.SubscribeTest")
	proto.RegisterType((*Test)(nil), "tests.Test")
	proto.RegisterType((*Credentials)(nil), "tests.Credentials")
	proto.RegisterType((*Connection)(nil), "tests.Connection")
	proto.RegisterType((*FakeTest)(nil), "tests.FakeTest")
	proto.RegisterType((*HasKeys)(nil), "tests.HasKeys")
	proto.RegisterType((*HasKeys_Item)(nil), "tests.HasKeys.Item")
	proto.RegisterMapType((map[string]string)(nil), "tests.HasKeys.Item.KeyEntry")
	proto.RegisterType((*DataTreePaths)(nil), "tests.DataTreePaths")
	proto.RegisterType((*DataTreePaths_QueryStep)(nil), "tests.DataTreePaths.QueryStep")
	proto.RegisterMapType((map[string]string)(nil), "tests.DataTreePaths.QueryStep.KeyEntry")
	proto.RegisterType((*DataTreePaths_TestQuery)(nil), "tests.DataTreePaths.TestQuery")
	proto.RegisterType((*DataTreePaths_ListQuery)(nil), "tests.DataTreePaths.ListQuery")
	proto.RegisterType((*DataTreePaths_RequiredPaths)(nil), "tests.DataTreePaths.RequiredPaths")
	proto.RegisterType((*SchemaPathComplete)(nil), "tests.SchemaPathComplete")
	proto.RegisterType((*GetSetTest)(nil), "tests.GetSetTest")
	proto.RegisterType((*GetSetValidationTest)(nil), "tests.GetSetValidationTest")
	proto.RegisterType((*GetSetValidationOper)(nil), "tests.GetSetValidationOper")
	proto.RegisterEnum("tests.GetSetValidationOper_OperResult", GetSetValidationOper_OperResult_name, GetSetValidationOper_OperResult_value)
}

func init() { proto.RegisterFile("proto/tests/tests.proto", fileDescriptor_tests_d7f4f41f086a4fc3) }

var fileDescriptor_tests_d7f4f41f086a4fc3 = []byte{
	// 1173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x5b, 0x6f, 0x1b, 0x45,
	0x14, 0xf6, 0xfa, 0xee, 0xe3, 0x4b, 0xd2, 0x69, 0x28, 0x5b, 0x03, 0x91, 0xb5, 0xa0, 0x36, 0x12,
	0xe0, 0x94, 0x10, 0x55, 0x2d, 0xa8, 0x48, 0xe4, 0xea, 0x2a, 0x51, 0x03, 0x93, 0x82, 0x78, 0x40,
	0x5a, 0x4d, 0xec, 0x93, 0xf5, 0xca, 0xde, 0x4b, 0x77, 0xc6, 0xa1, 0x7e, 0xe6, 0x9d, 0x47, 0x24,
	0x7e, 0x02, 0x0f, 0xfc, 0x09, 0x7e, 0x07, 0xbf, 0x84, 0x27, 0x34, 0x97, 0xbd, 0x58, 0x75, 0x83,
	0xe0, 0x65, 0xb5, 0x67, 0xce, 0xed, 0x9b, 0xef, 0x9c, 0x33, 0x33, 0xf0, 0x6e, 0x9c, 0x44, 0x22,
	0xda, 0x15, 0xc8, 0x05, 0xd7, 0xdf, 0xa1, 0x5a, 0x21, 0x35, 0x25, 0xf4, 0x1f, 0x79, 0xbe, 0x98,
	0x2e, 0xae, 0x86, 0xe3, 0x28, 0xd8, 0x8d, 0x62, 0x0c, 0xc7, 0x51, 0x78, 0xed, 0x7b, 0xbb, 0x5e,
	0x18, 0xf8, 0xbb, 0xda, 0x55, 0xfd, 0xca, 0x8f, 0x76, 0x74, 0x5a, 0xd0, 0x38, 0xc2, 0x6b, 0xb6,
	0x98, 0x0b, 0xe7, 0xe7, 0x0a, 0x74, 0x2f, 0x17, 0x57, 0x7c, 0x9c, 0xf8, 0x57, 0xf8, 0x12, 0xb9,
	0x20, 0x8f, 0xa0, 0x91, 0xe0, 0xab, 0x05, 0x72, 0x61, 0x5b, 0x03, 0x6b, 0xa7, 0xbd, 0x77, 0x6f,
	0xa8, 0x5c, 0x33, 0x2b, 0xaa, 0xb5, 0x34, 0x35, 0x23, 0x1f, 0x42, 0x77, 0x1e, 0x79, 0x6e, 0x82,
	0x3c, 0x8e, 0x42, 0x8e, 0xdc, 0x2e, 0x0f, 0xac, 0x9d, 0x26, 0xed, 0xcc, 0x23, 0x8f, 0xa6, 0x6b,
	0xe4, 0x03, 0x68, 0x5d, 0xb3, 0x19, 0xba, 0x12, 0xb3, 0x0d, 0x03, 0x6b, 0xa7, 0x35, 0x2a, 0xd1,
	0xa6, 0x5c, 0x52, 0x59, 0x9f, 0xc2, 0x46, 0xcc, 0xc4, 0xd4, 0xbd, 0x61, 0x73, 0x7f, 0xc2, 0x84,
	0x1f, 0x85, 0x76, 0x5b, 0x65, 0xef, 0x0d, 0xf5, 0x96, 0x0d, 0xe0, 0x51, 0x89, 0xf6, 0xa4, 0xe1,
	0xf7, 0x99, 0x1d, 0xf9, 0x18, 0x9a, 0x53, 0xc6, 0xdd, 0x19, 0x2e, 0xb9, 0xdd, 0x59, 0xf1, 0x19,
	0x31, 0x7e, 0x86, 0x4b, 0x3e, 0x2a, 0xd1, 0xc6, 0x54, 0xff, 0x92, 0x73, 0xb8, 0xcb, 0xc7, 0x53,
	0x0c, 0x98, 0xca, 0x36, 0x8e, 0x82, 0x78, 0x8e, 0x02, 0xed, 0xae, 0xf2, 0xbb, 0x6f, 0xfc, 0x2e,
	0x95, 0xc5, 0x37, 0x4c, 0x4c, 0x0f, 0x8d, 0xc1, 0xa8, 0x44, 0x49, 0xee, 0x97, 0xae, 0x92, 0xaf,
	0x60, 0x63, 0xc2, 0x04, 0x73, 0x45, 0x82, 0xe8, 0x4a, 0x0d, 0xb7, 0x7b, 0x2a, 0xd2, 0x56, 0x8a,
	0x9a, 0x09, 0xf6, 0x32, 0x41, 0x94, 0xb1, 0x24, 0x8e, 0xee, 0xa4, 0xb8, 0x70, 0x50, 0x87, 0x2a,
	0x4b, 0x3c, 0xee, 0xfc, 0x5e, 0x86, 0xaa, 0xa2, 0x61, 0x00, 0xed, 0x09, 0x4a, 0x9a, 0x63, 0x45,
	0x81, 0x2c, 0x40, 0x8b, 0x16, 0x97, 0x88, 0x0d, 0x0d, 0xe1, 0x07, 0x18, 0x2d, 0x84, 0xa2, 0xb9,
	0x46, 0x53, 0x91, 0xdc, 0x83, 0xba, 0x86, 0x68, 0x57, 0x94, 0x9b, 0x91, 0xc8, 0x67, 0x00, 0xe3,
	0x28, 0x0c, 0x71, 0xac, 0x42, 0x56, 0x15, 0xbe, 0x3b, 0x06, 0xdf, 0x61, 0xa6, 0xa0, 0x05, 0x23,
	0xb2, 0x0f, 0x2d, 0x9e, 0x96, 0x5b, 0x15, 0x2b, 0xdf, 0xd1, 0x4a, 0xb3, 0x8c, 0x4a, 0x34, 0x37,
	0x24, 0x9f, 0x40, 0xc3, 0x43, 0xe1, 0x72, 0x14, 0xa6, 0x76, 0x69, 0x96, 0x53, 0x14, 0x97, 0x28,
	0x8c, 0x43, 0xdd, 0x53, 0x12, 0x19, 0x16, 0x1b, 0x42, 0xd7, 0x6d, 0xc3, 0xd8, 0x9f, 0x98, 0xae,
	0x28, 0x76, 0x88, 0xe4, 0x4a, 0x2c, 0x63, 0x74, 0x18, 0xb4, 0x0f, 0x13, 0x9c, 0x60, 0x28, 0x7c,
	0x36, 0xe7, 0xa4, 0x0f, 0xcd, 0x04, 0x79, 0x34, 0xbf, 0xc1, 0xc4, 0xd0, 0x95, 0xc9, 0x52, 0xb7,
	0xe0, 0x98, 0x84, 0x2c, 0x40, 0x45, 0x56, 0x8b, 0x66, 0xb2, 0xd4, 0xc5, 0x8c, 0xf3, 0x9f, 0xa2,
	0x64, 0x62, 0xf8, 0xca, 0x64, 0xe7, 0x17, 0x0b, 0x20, 0x67, 0x46, 0x12, 0x2b, 0x58, 0xe2, 0xa1,
	0x30, 0x09, 0x8c, 0x24, 0x4b, 0xc1, 0x26, 0x93, 0x04, 0x39, 0x37, 0xd1, 0x53, 0x91, 0xec, 0x43,
	0x7b, 0x9c, 0x63, 0x54, 0xf1, 0xdb, 0x7b, 0x24, 0xe5, 0x3c, 0xd7, 0xd0, 0xa2, 0x59, 0xb1, 0xb4,
	0xd5, 0x95, 0xd2, 0x3a, 0xdb, 0xd0, 0x4c, 0x39, 0x21, 0x04, 0xaa, 0x12, 0xa8, 0xc2, 0xd2, 0xa4,
	0xea, 0xdf, 0xf9, 0xd3, 0x82, 0x86, 0x69, 0x76, 0xb2, 0x2d, 0xf5, 0x62, 0x6a, 0x86, 0x17, 0xf4,
	0xf0, 0xca, 0x76, 0xa3, 0x6a, 0x9d, 0x3c, 0x84, 0xaa, 0x2f, 0x30, 0xb0, 0xcb, 0x83, 0xca, 0x4e,
	0x7b, 0xef, 0xee, 0xea, 0xa8, 0x0c, 0x9f, 0x0b, 0x0c, 0xa8, 0x32, 0xe8, 0x87, 0x50, 0x95, 0x12,
	0x19, 0x42, 0x65, 0x86, 0x4b, 0xdb, 0x52, 0xf6, 0xef, 0xaf, 0xb1, 0x1f, 0x9e, 0xe1, 0xf2, 0x38,
	0x14, 0xc9, 0x92, 0x4a, 0xc3, 0xfe, 0x63, 0x68, 0xa6, 0x0b, 0x64, 0x33, 0xf5, 0x95, 0xf4, 0xc8,
	0x5f, 0xb2, 0x05, 0xb5, 0x1b, 0x36, 0x5f, 0xa4, 0x05, 0xd1, 0xc2, 0x17, 0xe5, 0x27, 0x96, 0xf3,
	0x5b, 0x0d, 0xba, 0x2b, 0xf3, 0x42, 0xbe, 0x84, 0x96, 0xcc, 0xe6, 0x46, 0xb1, 0x29, 0x6e, 0x7b,
	0x6f, 0x7b, 0xdd, 0x60, 0x0d, 0x25, 0x31, 0xdf, 0x2e, 0x30, 0x59, 0xd2, 0xa6, 0x54, 0x5f, 0xc4,
	0x98, 0xf4, 0xff, 0xb0, 0xa0, 0xa5, 0xd6, 0x2e, 0x05, 0xc6, 0x92, 0x35, 0xd5, 0x06, 0x1a, 0x89,
	0xfa, 0x27, 0x4f, 0x35, 0x38, 0x4d, 0xc4, 0xc3, 0xb5, 0x81, 0xb3, 0x00, 0xab, 0x7b, 0x24, 0xf7,
	0xa1, 0x39, 0xc3, 0xa5, 0xab, 0x42, 0xea, 0xee, 0x69, 0xcc, 0x70, 0xf9, 0x82, 0x05, 0xf8, 0x7f,
	0xb7, 0xdf, 0xff, 0xcb, 0x82, 0x56, 0xb6, 0x0f, 0xb2, 0x0f, 0x35, 0x2e, 0x30, 0xe6, 0x86, 0xf6,
	0xed, 0xdb, 0xd1, 0x51, 0x6d, 0x4c, 0x8e, 0xa0, 0x2b, 0x27, 0x70, 0xee, 0x73, 0xa1, 0xcf, 0xc3,
	0xf2, 0x2d, 0xa4, 0x9d, 0xfb, 0x26, 0xd9, 0xa8, 0x44, 0xdb, 0x1e, 0x0a, 0x29, 0xab, 0x0e, 0x3a,
	0x83, 0x9e, 0x3c, 0xda, 0xfd, 0x04, 0x27, 0xe6, 0x50, 0xd3, 0x0d, 0xec, 0xac, 0x0d, 0x43, 0x8d,
	0x69, 0x76, 0xc4, 0x25, 0xc5, 0x85, 0x74, 0x6c, 0xfb, 0x08, 0xad, 0x2c, 0xa1, 0xa4, 0xef, 0x86,
	0x25, 0x6e, 0xa1, 0x22, 0x8d, 0x1b, 0x96, 0x48, 0xfa, 0xc8, 0x33, 0x80, 0x10, 0x5f, 0x0b, 0xf7,
	0x95, 0x34, 0xbc, 0x15, 0x7f, 0x5e, 0xf4, 0x96, 0xf4, 0x50, 0xbf, 0xfd, 0xef, 0xa0, 0xbb, 0x02,
	0x88, 0x38, 0x50, 0x8f, 0x13, 0xbc, 0xf6, 0x5f, 0xaf, 0x19, 0x08, 0xa3, 0x21, 0x03, 0xa8, 0xe9,
	0x7d, 0xea, 0x56, 0x28, 0x9a, 0x68, 0x85, 0xf3, 0x03, 0x90, 0x37, 0x2f, 0x85, 0x42, 0xec, 0xf2,
	0x5b, 0x63, 0xe7, 0xe3, 0x58, 0x59, 0x37, 0x8e, 0xce, 0x8f, 0x00, 0xf9, 0xf1, 0x48, 0x4e, 0x60,
	0x43, 0x36, 0x7b, 0xf1, 0x1a, 0xd4, 0xc7, 0xef, 0x7b, 0x2b, 0x47, 0x69, 0x7e, 0xfb, 0x99, 0x63,
	0xb2, 0x27, 0xbd, 0xf2, 0xd5, 0xec, 0x62, 0xf9, 0xd5, 0x82, 0xad, 0x75, 0x2e, 0xe4, 0x08, 0x36,
	0xfc, 0xd0, 0x97, 0xe7, 0x8e, 0xcf, 0xb1, 0x38, 0x60, 0x6f, 0x4b, 0x24, 0x67, 0x8a, 0xf6, 0x72,
	0x1f, 0x29, 0x93, 0x27, 0xc5, 0x01, 0x2d, 0xff, 0xbb, 0x7f, 0x36, 0x9d, 0xce, 0xdf, 0x95, 0x37,
	0x81, 0xa9, 0x90, 0x1f, 0x41, 0x85, 0x63, 0xfa, 0xf4, 0xd8, 0x34, 0x4f, 0x0f, 0x14, 0xe6, 0xd1,
	0x31, 0x2a, 0x51, 0xa9, 0x26, 0x9f, 0xc2, 0x9d, 0x71, 0x14, 0x04, 0x51, 0x28, 0x6f, 0x9b, 0xf4,
	0xb9, 0x52, 0x36, 0xaf, 0x8a, 0x4d, 0xad, 0xba, 0xcc, 0x34, 0xe4, 0x19, 0xd4, 0x39, 0x0a, 0x37,
	0x9a, 0x29, 0x36, 0x7b, 0x7b, 0x0f, 0x6e, 0x01, 0x39, 0x54, 0x48, 0x91, 0x2f, 0xe6, 0x82, 0xd6,
	0x38, 0x8a, 0x8b, 0x99, 0xc4, 0xe4, 0x65, 0x97, 0x9a, 0xc1, 0x74, 0x9a, 0x63, 0xb2, 0xa8, 0x54,
	0x17, 0x30, 0x79, 0x39, 0xa6, 0x8e, 0xc2, 0x64, 0xa5, 0x98, 0x4e, 0x57, 0x30, 0x79, 0x1a, 0xd3,
	0xd6, 0x7f, 0xc3, 0xe4, 0x29, 0x4c, 0x8f, 0xa1, 0x23, 0xdd, 0xd3, 0x47, 0x97, 0xfd, 0x8e, 0xb9,
	0x71, 0x73, 0x70, 0x5a, 0x31, 0x2a, 0xab, 0xe1, 0x4e, 0x45, 0xb2, 0x0b, 0xa4, 0x88, 0xd2, 0x78,
	0xdf, 0x53, 0x30, 0xcb, 0xf4, 0x4e, 0x01, 0xa6, 0x56, 0x39, 0x0f, 0x00, 0xf2, 0xec, 0xa4, 0x03,
	0xcd, 0x17, 0x17, 0xee, 0x31, 0xa5, 0x17, 0x74, 0xb3, 0x44, 0x00, 0xea, 0x27, 0x5f, 0x3f, 0x3f,
	0x3f, 0x3e, 0xda, 0xb4, 0x0e, 0x3a, 0x00, 0x79, 0x2d, 0xa4, 0x94, 0xb3, 0x70, 0xd0, 0x85, 0x76,
	0x21, 0xdb, 0x55, 0x5d, 0x3d, 0x43, 0x3f, 0xff, 0x27, 0x00, 0x00, 0xff, 0xff, 0xdd, 0x20, 0xf7,
	0x7b, 0xda, 0x0a, 0x00, 0x00,
}
