# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/report/report.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from github.com.openconfig.gnmi.proto.gnmi import gnmi_pb2 as github_dot_com_dot_openconfig_dot_gnmi_dot_proto_dot_gnmi_dot_gnmi__pb2
from github.com.openconfig.gnmitest.proto.tests import tests_pb2 as github_dot_com_dot_openconfig_dot_gnmitest_dot_proto_dot_tests_dot_tests__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/report/report.proto',
  package='report',
  syntax='proto3',
  serialized_pb=_b('\n\x19proto/report/report.proto\x12\x06report\x1a\x30github.com/openconfig/gnmi/proto/gnmi/gnmi.proto\x1a\x36github.com/openconfig/gnmitest/proto/tests/tests.proto\"S\n\x17SubscribeResponseResult\x12)\n\x08response\x18\x01 \x01(\x0b\x32\x17.gnmi.SubscribeResponse\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x82\x01\n\x13SubscribeTestResult\x12\x32\n\tresponses\x18\x01 \x03(\x0b\x32\x1f.report.SubscribeResponseResult\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12(\n\x06status\x18\x03 \x01(\x0e\x32\x18.report.CompletionStatus\"\x81\x01\n\nTestResult\x12\x19\n\x04test\x18\x01 \x01(\x0b\x32\x0b.tests.Test\x12\x1e\n\x06result\x18\x02 \x01(\x0e\x32\x0e.report.Status\x12\x30\n\tsubscribe\x18\n \x01(\x0b\x32\x1b.report.SubscribeTestResultH\x00\x42\x06\n\x04type\"i\n\x08Instance\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12 \n\x04test\x18\x02 \x01(\x0b\x32\x12.report.TestResult\x12&\n\nextensions\x18\x03 \x03(\x0b\x32\x12.report.TestResult\"Y\n\rInstanceGroup\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\"\n\x08instance\x18\x02 \x03(\x0b\x32\x10.report.Instance\x12\x0f\n\x07skipped\x18\x03 \x01(\x08\"0\n\x06Report\x12&\n\x07results\x18\x01 \x03(\x0b\x32\x15.report.InstanceGroup*]\n\x10\x43ompletionStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08\x46INISHED\x10\x01\x12\x12\n\x0e\x45\x41RLY_FINISHED\x10\x02\x12\r\n\tRPC_ERROR\x10\x03\x12\x0b\n\x07TIMEOUT\x10\x04**\n\x06Status\x12\t\n\x05UNSET\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x08\n\x04\x46\x41IL\x10\x02\x62\x06proto3')
  ,
  dependencies=[github_dot_com_dot_openconfig_dot_gnmi_dot_proto_dot_gnmi_dot_gnmi__pb2.DESCRIPTOR,github_dot_com_dot_openconfig_dot_gnmitest_dot_proto_dot_tests_dot_tests__pb2.DESCRIPTOR,])

_COMPLETIONSTATUS = _descriptor.EnumDescriptor(
  name='CompletionStatus',
  full_name='report.CompletionStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FINISHED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EARLY_FINISHED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RPC_ERROR', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIMEOUT', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=741,
  serialized_end=834,
)
_sym_db.RegisterEnumDescriptor(_COMPLETIONSTATUS)

CompletionStatus = enum_type_wrapper.EnumTypeWrapper(_COMPLETIONSTATUS)
_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='report.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAIL', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=836,
  serialized_end=878,
)
_sym_db.RegisterEnumDescriptor(_STATUS)

Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
UNKNOWN = 0
FINISHED = 1
EARLY_FINISHED = 2
RPC_ERROR = 3
TIMEOUT = 4
UNSET = 0
SUCCESS = 1
FAIL = 2



_SUBSCRIBERESPONSERESULT = _descriptor.Descriptor(
  name='SubscribeResponseResult',
  full_name='report.SubscribeResponseResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='report.SubscribeResponseResult.response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='report.SubscribeResponseResult.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=226,
)


_SUBSCRIBETESTRESULT = _descriptor.Descriptor(
  name='SubscribeTestResult',
  full_name='report.SubscribeTestResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responses', full_name='report.SubscribeTestResult.responses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='report.SubscribeTestResult.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='report.SubscribeTestResult.status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=359,
)


_TESTRESULT = _descriptor.Descriptor(
  name='TestResult',
  full_name='report.TestResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='test', full_name='report.TestResult.test', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='report.TestResult.result', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subscribe', full_name='report.TestResult.subscribe', index=2,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='report.TestResult.type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=362,
  serialized_end=491,
)


_INSTANCE = _descriptor.Descriptor(
  name='Instance',
  full_name='report.Instance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='report.Instance.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test', full_name='report.Instance.test', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extensions', full_name='report.Instance.extensions', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=493,
  serialized_end=598,
)


_INSTANCEGROUP = _descriptor.Descriptor(
  name='InstanceGroup',
  full_name='report.InstanceGroup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='report.InstanceGroup.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instance', full_name='report.InstanceGroup.instance', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skipped', full_name='report.InstanceGroup.skipped', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=600,
  serialized_end=689,
)


_REPORT = _descriptor.Descriptor(
  name='Report',
  full_name='report.Report',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='report.Report.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=691,
  serialized_end=739,
)

_SUBSCRIBERESPONSERESULT.fields_by_name['response'].message_type = github_dot_com_dot_openconfig_dot_gnmi_dot_proto_dot_gnmi_dot_gnmi__pb2._SUBSCRIBERESPONSE
_SUBSCRIBETESTRESULT.fields_by_name['responses'].message_type = _SUBSCRIBERESPONSERESULT
_SUBSCRIBETESTRESULT.fields_by_name['status'].enum_type = _COMPLETIONSTATUS
_TESTRESULT.fields_by_name['test'].message_type = github_dot_com_dot_openconfig_dot_gnmitest_dot_proto_dot_tests_dot_tests__pb2._TEST
_TESTRESULT.fields_by_name['result'].enum_type = _STATUS
_TESTRESULT.fields_by_name['subscribe'].message_type = _SUBSCRIBETESTRESULT
_TESTRESULT.oneofs_by_name['type'].fields.append(
  _TESTRESULT.fields_by_name['subscribe'])
_TESTRESULT.fields_by_name['subscribe'].containing_oneof = _TESTRESULT.oneofs_by_name['type']
_INSTANCE.fields_by_name['test'].message_type = _TESTRESULT
_INSTANCE.fields_by_name['extensions'].message_type = _TESTRESULT
_INSTANCEGROUP.fields_by_name['instance'].message_type = _INSTANCE
_REPORT.fields_by_name['results'].message_type = _INSTANCEGROUP
DESCRIPTOR.message_types_by_name['SubscribeResponseResult'] = _SUBSCRIBERESPONSERESULT
DESCRIPTOR.message_types_by_name['SubscribeTestResult'] = _SUBSCRIBETESTRESULT
DESCRIPTOR.message_types_by_name['TestResult'] = _TESTRESULT
DESCRIPTOR.message_types_by_name['Instance'] = _INSTANCE
DESCRIPTOR.message_types_by_name['InstanceGroup'] = _INSTANCEGROUP
DESCRIPTOR.message_types_by_name['Report'] = _REPORT
DESCRIPTOR.enum_types_by_name['CompletionStatus'] = _COMPLETIONSTATUS
DESCRIPTOR.enum_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubscribeResponseResult = _reflection.GeneratedProtocolMessageType('SubscribeResponseResult', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIBERESPONSERESULT,
  __module__ = 'proto.report.report_pb2'
  # @@protoc_insertion_point(class_scope:report.SubscribeResponseResult)
  ))
_sym_db.RegisterMessage(SubscribeResponseResult)

SubscribeTestResult = _reflection.GeneratedProtocolMessageType('SubscribeTestResult', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIBETESTRESULT,
  __module__ = 'proto.report.report_pb2'
  # @@protoc_insertion_point(class_scope:report.SubscribeTestResult)
  ))
_sym_db.RegisterMessage(SubscribeTestResult)

TestResult = _reflection.GeneratedProtocolMessageType('TestResult', (_message.Message,), dict(
  DESCRIPTOR = _TESTRESULT,
  __module__ = 'proto.report.report_pb2'
  # @@protoc_insertion_point(class_scope:report.TestResult)
  ))
_sym_db.RegisterMessage(TestResult)

Instance = _reflection.GeneratedProtocolMessageType('Instance', (_message.Message,), dict(
  DESCRIPTOR = _INSTANCE,
  __module__ = 'proto.report.report_pb2'
  # @@protoc_insertion_point(class_scope:report.Instance)
  ))
_sym_db.RegisterMessage(Instance)

InstanceGroup = _reflection.GeneratedProtocolMessageType('InstanceGroup', (_message.Message,), dict(
  DESCRIPTOR = _INSTANCEGROUP,
  __module__ = 'proto.report.report_pb2'
  # @@protoc_insertion_point(class_scope:report.InstanceGroup)
  ))
_sym_db.RegisterMessage(InstanceGroup)

Report = _reflection.GeneratedProtocolMessageType('Report', (_message.Message,), dict(
  DESCRIPTOR = _REPORT,
  __module__ = 'proto.report.report_pb2'
  # @@protoc_insertion_point(class_scope:report.Report)
  ))
_sym_db.RegisterMessage(Report)


# @@protoc_insertion_point(module_scope)
